### PR TITLE
fix "Encoding::UndefinedConversionError:  from ASCII-8BIT to UTF-8"

### PR DESCRIPTION
**Pull request by gururuby**

### CODE REVIEW

**Comment by ondra-m** [comment]
Please write an example when it failed.

**Comment by gururuby** [comment]
`$sc.parallelize(["jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj"])
Encoding::UndefinedConversionError: "\x82" from ASCII-8BIT to UTF-8
`
This is the same error as here https://github.com/ondra-m/ruby-spark/issues/27

**Comment by ondra-m** [comment]
It works for me. What serializator do you user?

```ruby
  $sc.default_serializer
```

**Comment by gururuby** [comment]
I use oj serializer

**Comment by ondra-m** [comment]
Please write full example with your configurations. Oj works for me.

**Pull request closed without merging**
